const EXPRIE_TOKEN = "1d";
const EXPRIE_COOKIE = 24 * 60 * 60 * 1000
const FOLDER_UPLOAD_AVATARS = "avatars";
const FILE_SIZE_AVATAR_LIMIT = 5 * 1024 * 1024; // 5MB

const MIN_USERNAME_LENGTH = 3;
const MAX_USERNAME_LENGTH = 20;
const MIN_PASSWORD_LENGTH = 6;
const MAX_PASSWORD_LENGTH = 15;
const MIN_FULLNAME_LENGTH = 3;
const MAX_FULLNAME_LENGTH = 50;


export { EXPRIE_TOKEN, EXPRIE_COOKIE, FOLDER_UPLOAD_AVATARS, FILE_SIZE_AVATAR_LIMIT, MIN_USERNAME_LENGTH, MAX_USERNAME_LENGTH, MIN_PASSWORD_LENGTH, MAX_PASSWORD_LENGTH, MIN_FULLNAME_LENGTH, MAX_FULLNAME_LENGTH }